### ISSUE TITLE
Make properties of StartupOptions public

### ISSUE THREAD

**Issue by bennetrr** [wemogy/libs-aspnet#55]
When using a custom setup instead of `app.UseDefaultSetup`, the user needs to access the properties of the `StartupOptions` class. Currently, the properties are private.

**Comment by robinmanuelthiel** [comment]
Not planned. We now have functionality to pass the whole `StartupOptions` object to each of our helper methods. The reason, why we don't want to expose or pass stuff like `MonitoringEnvironment` is, that the `StartupOptions` object has helper methods that sets our defaults. So please always instantiate `StartupOptions` and then just pass them.
